name: AutoRelease

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.24"

      - run: CGO_ENABLED=0 go build -o workman . && tar -zcf workman_linux_amd64.tar.gz workman
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o workman.exe . && tar -zcf workman_windows_amd64.tar.gz workman.exe
      # - run: zip -qq workman_windows_amd64.zip workman.exe
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o workman . && tar -zcf workman_darwin_amd64.tar.gz workman

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            workman_linux_amd64.tar.gz
            workman_windows_amd64.tar.gz
            workman_darwin_amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
